Add ignore facility for sql files to tab checker, test for GNU find

diff --git a/tools/rules/tabs b/tools/rules/tabs
--- a/tools/rules/tabs
+++ b/tools/rules/tabs
@@ -8,15 +8,35 @@ source tools/rule_helpers
 # Counter to keep track of number of files with tabs
 ERRORS=0
 
+# space-separated list of glob patterns for file names where we allow tabs
+TABS_ALLOWED_IN="*.sql"
 
-for dir in ${DIRS[@]}; do
-    # trailing $ in string literal activates c-style
-    # escape sequences
-    TAB_REGEX=$'\t'
-    EVAL_CMD="find \""$dir"\" -type f \( ${FIND_STR} \) \
-      -exec egrep -l \"$TAB_REGEX\" {} \;"
-    for file in $(eval "$EVAL_CMD"); do
-        echo "Tab character found in $file, alerting authorities."
-        exit 1
-    done
-done
+if has_gnu_find ; then
+
+  # Create a condition for find that contains
+  # -o -iname "$pattern"
+  # for each pattern in TABS_ALLOWED_IN
+  # This is later used under a negation, hence the initial value being false
+  exceptions="-false"
+  for pattern in $TABS_ALLOWED_IN ; do
+    exceptions="${exceptions} -o -iname \"${pattern}\""
+  done
+
+
+
+  for dir in ${DIRS[@]}; do
+      # trailing $ in string literal activates c-style
+      # escape sequences
+      TAB_REGEX=$'\t'
+      EVAL_CMD="find \""$dir"\" \
+        -type f \( ${FIND_STR} \) \
+        -exec egrep -l \"$TAB_REGEX\" {} \; \
+        -not \( $exceptions \)"
+      for file in $(eval "$EVAL_CMD"); do
+          echo "Tab character found in $file, alerting authorities."
+          exit 1
+      done
+  done
+else
+  echo "Warning: GNU find not found, skipping test"
+fi
