Whitelist for whitespace check (#465)
Fixes #464.

diff --git a/tools/rules/trailing_whitespace b/tools/rules/trailing_whitespace
--- a/tools/rules/trailing_whitespace
+++ b/tools/rules/trailing_whitespace
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Checks whether source files contain trailing script.
+# Checks whether any textual files contain trailing whitespace.
 #
 # By passing the argument "strip" the script attempts to automatically
 # strip trailing white space.
@@ -17,22 +17,35 @@ DIRS=("core" "bin" "tests" "examples")
 # Counter to keep track of number of files with trailing white space.
 ERRORS=0
 
+
+PATTERNS=("*.ml" "*.mli" "*.mly" "*.mll" "*.py" "*.pl" "*.html" "*.js"\
+          "*.txt" "*.links" "*.css" "*.sh" "*.el" "*.vim" "*.opam"\
+          "dune-project" "dune")
+
+# https://stackoverflow.com/questions/1527049/how-can-i-join-elements-of-an-array-in-bash
+SEP=" -o -name "
+FIND_STR="$( printf "${SEP}\"%s\"" "${PATTERNS[@]}" )"
+FIND_STR="${FIND_STR:${#SEP}}"
+FIND_STR="-name $FIND_STR"
+echo ${FIND_STR}
+
 for dir in ${DIRS[@]}; do
-    for file in $(find "$dir"  -type f -not -name "*.pdf" -exec egrep -l " +$" {} \;); do
-        echo -n "$file"
-        if [[ $STRIP -eq 1 ]]; then
-            echo -n "..."
-            sed -i 's/[ \t]*$//' $file
-            if [[ $? -eq 0 ]]; then
-                echo " CLEANED."
-            else
-                echo " FAILED."
-                ERRORS=$((ERRORS+1))
-            fi
-        else
-            echo ""
-            ERRORS=$((ERRORS+1))
-        fi
+    for file in $(eval "find \""$dir"\" -type f \( ${FIND_STR} \) \
+      -exec egrep -l \" +$\" {} \;"); do
+          echo -n "$file"
+          if [[ $STRIP -eq 1 ]]; then
+              echo -n "..."
+              sed -i 's/[ \t]*$//' $file
+              if [[ $? -eq 0 ]]; then
+                  echo " CLEANED."
+              else
+                  echo " FAILED."
+                  ERRORS=$((ERRORS+1))
+              fi
+          else
+              echo ""
+              ERRORS=$((ERRORS+1))
+          fi
     done
 done
 
