Database tests can now be expected to be broken.
A first step towards allowing more complex test scenarios in
the testsuite. See #64

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -5,13 +5,15 @@
 #
 # https://github.com/links-lang/links/wiki/Running-the-test-suite
 
-# Control sequences used to display text in red
-STARTCOLOR="\e[31m";
-ENDCOLOR="\e[0m";
 
-ret=0
+DATABASE_TEST_DIR=tests/database   # Location of database tests
+SHREDDING_TEST_DIR=tests/shredding # Location of database tests
+ret=0                              # Return code. If <> 0 then some tests failed
+STARTCOLOR="\e[31m"                # Control sequence to enable red text
+ENDCOLOR="\e[0m"                   # Control sequence to enable normal text
 
-if [[ $1 != "db-only" ]]; then
+# Don't run normal tests if user passed in "db-only" flag
+if [[ "$1" != "db-only" ]]; then
     for i in tests/*.tests; do
         cmnd="./test-harness $i"
         echo cmnd=$cmnd
@@ -23,24 +25,34 @@ if [[ $1 != "db-only" ]]; then
     done
 fi
 
-if [[ $1 != "no-db" ]]; then
-    if [[ ! -e tests/database/config ]]; then
+# Run database tests stored in a directory passed in as argument.
+# Assumes that the directory contains:
+#  1. either `config` containing actual database configuration or
+#     `config.sample` containing a default database configuration.
+#  2. `testsuite.config` containing a list of tests to run
+run_database_testsuite () {
+    # Check if database configuration exists. If not the creating from
+    # a default config.sample file
+    if [[ ! -e $1/config ]]; then
       echo -en "$STARTCOLOR"
-      echo -e  "Creating default database configuration tests/database/config"
-      echo -e  "from tests/database/config.sample"
+      echo -e  "Creating default database test configuration $1/config"
+      echo -e  "from $1/config.sample"
       echo -e  "Please customize to match your local database setup."
       echo -en "$ENDCOLOR"
-      cp tests/database/config.sample tests/database/config
+      cp $1/config.sample $1/config
     fi
 
+    # Check whether the config file specifies a user name to access the
+    # database.  If so, use it with psql.
     user_string=""
-    user=`grep database_args tests/database/config \
+    user=`grep database_args $1/config \
           | sed 's/database_args=[^:]*:[^:]*:\([^:]*\):.*/\1/'`
     if [ "$user" != "" ]; then
         user_string="-U $user"
     fi
 
-    for s in tests/database/*.sql; do
+    # Prepare the database by running all the *.sql files
+    for s in $1/*.sql; do
         cmnd="psql -v $user_string ON_ERROR_STOP=1 -q -d links -f $s"
         echo cmnd=$cmnd
         eval $cmnd
@@ -51,56 +63,37 @@ if [[ $1 != "no-db" ]]; then
         fi
     done
 
-    for t in tests/database/*.links; do
-        cmnd="./links --config=tests/database/config $t"
+    # Run tests specified in testsuite.config
+    while read t; do
+        expect_broken=0
+        line=($t)
+        # Check if a test is specified as broken.  This doesn't check that the
+        # word preceeding test name is actually "BROKEN". So putting any word
+        # before the test name will turn that test into "expected broken".
+        if (( ${#line[@]} > 1 )); then
+          t=${line[1]}
+          expect_broken=1
+        fi
+        cmnd="./links --config=$1/config $1/$t.links"
         echo cmnd=$cmnd
         eval $cmnd
         ret_code=$?
-        if [ $ret_code != 0 ]; then
+        # Fail if a test should pass but didn't or shouldn't pass but did
+        if [[ ($ret_code -ne 0 && expect_broken -eq 0) || ($ret_code -eq 0 && expect_broken -ne 0) ]]; then
             echo -e "$STARTCOLOR\rFAILED TEST $t$ENDCOLOR"
             ret=1
         fi
-    done
+    done < "$1/testsuite.config"
+}
+
+# Don't run database tests if user passed in "no-db" flag
+if [[ "$1" != "no-db" ]]; then
+    run_database_testsuite $DATABASE_TEST_DIR
 fi
 
+# Run shredding tests only if user called for them explicitly
 if [ "$1" == "shredding" -o "$2" == "shredding" ]; then
-    if [[ ! -e tests/shredding/config ]]; then
-      echo -en "$STARTCOLOR"
-      echo -e  "Creating default shredding configuration tests/shredding/config"
-      echo -e  "from tests/shredding/config.sample"
-      echo -e  "Please customize to match your local database setup."
-      echo -en "$ENDCOLOR"
-      cp tests/shredding/config.sample tests/shredding/config
-    fi
-
-    user_string=""
-    user=`grep database_args tests/shredding/config \
-          | sed 's/database_args=[^:]*:[^:]*:\([^:]*\):.*/\1/'`
-    if [ "$user" != "" ]; then
-        user_string="-U $user"
-    fi
-
-    for s in tests/shredding/*.sql; do
-        cmnd="psql -v $user_string ON_ERROR_STOP=1 -q -d links -f $s"
-        echo cmnd=$cmnd
-        eval $cmnd
-        ret_code=$?
-        if [ $ret_code != 0 ]; then
-            echo "FAILED DATABASE PREPARATION $s"
-            ret=1
-        fi
-    done
-
-    for t in tests/shredding/*.links; do
-        cmnd="./links --config=tests/shredding/config $t"
-        echo cmnd=$cmnd
-        eval $cmnd
-        ret_code=$?
-        if [ $ret_code != 0 ]; then
-            echo "FAILED TEST $t"
-            ret=1
-        fi
-    done
+    run_database_testsuite $SHREDDING_TEST_DIR
 fi
 
 exit $ret
