Get rid of expect business, write tests in Links

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -12,14 +12,24 @@ for i in tests/*.tests; do
     fi
 done
 
-cd "tests/database"
-for t in *.exp; do
-    cmnd="expect -f $t"
+for s in tests/database/*.sql; do
+    cmnd="psql -v ON_ERROR_STOP=1 -q -U postgres -d links -f $s"
     echo cmnd=$cmnd
     eval $cmnd
     ret_code=$?
     if [ $ret_code != 0 ]; then
-        echo "FAILED $t"
+        echo "FAILED DATABASE PREPARATION $s"
+        ret=1
+    fi
+done
+
+for t in tests/database/*.links; do
+    cmnd="./links --config=tests/database/config $t"
+    echo cmnd=$cmnd
+    eval $cmnd
+    ret_code=$?
+    if [ $ret_code != 0 ]; then
+        echo "FAILED TEST $t"
         ret=1
     fi
 done
